# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ri40N2QEmMMr6NkhAhxeuI8V5hADKKsN
"""

class Human:
  def __init__(self):
    self.name = ""

  def setinfo(self, name, age):
    self.name = name
    self.age = 10

  def printinfo(self):
    print(f"名前：{self.name}")
    print(f"年齢：{self.age}")

human = Human()
human.setinfo("はな", 10)
human.printinfo()