# -*- coding: utf-8 -*-
"""kadai_008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qX1gsfMLRshQ49A1UqT8j5M0PVokp8vD
"""

import random
var = random.randint(1, 100)

if var % 3 ==0 and var % 5 == 0:
  print("FizzBuzz")
elif var % 3 == 0:
  print("Fizz")
elif var % 5 ==0:
  print("Buzz")
else:
  print(var)