# -*- coding: utf-8 -*-
"""kadai_013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K9C1kvejTh-8m9BZn_horIVO_ToUAPwI
"""

def price_caluclation(price, tax): #taxは「x」%で入力（%を入力しない）
  total = price + price * (tax/100)
  print(total)

price_caluclation(1000, 10)