# -*- coding: utf-8 -*-
"""kadi_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X9awVcI3POrbfJ92DWRs0fRCl9GyGgM1
"""

top = 10
bottom = 20
height = 5

square = (top + bottom) * height / 2
print(str(square) + "cm²")