# -*- coding: utf-8 -*-
"""kadai_017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SXzRF7XF4awVfsjSHExVLHMQ5M2kxAV7
"""



class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def check_adult(age):
    if age >= 20:
      print("大人です")
    else :
      print("大人ではありません")

hanako = Human("花子", 10)
taro = Human("太郎", 20)
yuki = Human("雪", 40)

human_list = [hanako.age, taro.age, yuki.age]

for member in human_list:
  Human.check_adult(member)