# -*- coding: utf-8 -*-
"""kadai_011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pj57Bs27QAwe-QhWpQ6kSMbu8OLQn03X
"""



list = ["水","金","地","火","木","土","天","海","冥"]

i = 0

while i != 2:
  for planet in list:
    print(planet)
  i = i + 1